development:
  host: dev.example.com
  email: john@doe.net
  password: easyone
staging:
  host: staging.example.com
  email: john@doe.net
  password: easyone
production:
  host: livingwatercrc.herokuapp.com
  email: jhwang@livingwatercrc.org
  password: jUd9IhDRtMbX
