development:
  host: localhost:3000
  email: jhwang@livingwatercrc.org
  password: password
staging:
  host: staging.example.com
  email: john@doe.net
  password: easyone
production:
  host: livingwatercrc.herokuapp.com
  email: jhwang@livingwatercrc.org
  password: jUd9IhDRtMbX
