site:
  name: Goodberry

  locales: [en]

  seo_title: "Bible Study &amp; Media Library for Churches : Goodberry.net"
  meta_keywords: "Bible Study & Media Library for Churches : Goodberry.net"
  meta_description: "Goodberry is a bible study, media (DVD, VHS, Audio, Kit) lending library for churches."

  pages:
    - index: # page path (the template can edited here app/views/pages/index.liquid)
        title: Home page
        published: true

    - landing:
        published: true
        listed: false
    - inner:
        published: true
        listed: false

    - 404:
        title: Page not found

    - about:
        published: true
        title: About Goodberry
        listed: true

    - blog:
        published: true
        title: Blog
        listed: true
    - blog/content_type_template:
        templatized: true
        published: true
        title: Template of an article
        model: articles
    - articles/rss:
        published: true
        title: rss feed
        listed: false
        format: rss