site:
  name: Goodberry

  locales: [en]

  seo_title: "Liquid Conference"
  meta_keywords: ""
  meta_description: ""

  pages:
    - index: # page path (the template can edited here app/views/pages/index.liquid)
        title: Home page
        published: true
        listed: true

    - landing:
        published: true
        listed: false
    - inner:
        published: true
        listed: false

    - 404:
        title: Page not found

    - home:
        published: true
        title: Home
        listed: true
        redirect_url: /

    - about:
        published: true
        title: About
        listed: true

    - blog:
        published: true
        title: Blog
        listed: true
    - blog/content_type_template:
        templatized: true
        published: true
        title: Template of an article
        model: articles
    - articles/rss:
        published: true
        title: rss feed
        listed: false
        format: rss
